#!/bin/bash
[ -z "$stack" ] && echo "ERROR You need to setup a \"stack\" variable" && exit 1;

## Sets the current DIR.  Then we can reference files relative to DIR,
## thus letting this script to run from ANY dir.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

aws cloudformation delete-stack \
  --stack-name $stack

  aws cloudformation wait stack-delete-complete \
    --stack-name $stack
