#!/bin/bash

stack=markdown-tatum
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

aws cloudformation update-stack \
  --stack-name $stack \
  --template-body file://$DIR/../cloud.yaml \
  --capabilities CAPABILITY_IAM && \

  aws cloudformation wait stack-update-complete \
    --stack-name $stack
